# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e63e2bb57213ab0fa29d96e0b710494608124c88a4d5262b4bbef6d9108cc682440cdafcaf0ba82dc38cfcf4af156bf87952c98c2047199055ad30dcb37caf65

test:
  secret_key_base: f4fe459e256fbc911ecb1b0009b4489d7e96f242bccd01bee24426186012433593f0307376cc15bb3e370e0c2b235fc1ee4f3c2990bc77977a0d213f84f35b65

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
